profilerView:
  className: SerginhoLD\Phalcon\WebProfiler\View\View
  shared: true
  calls:
    - method: registerEngines
      arguments:
        - type: parameter
          value:
            .volt: profilerVolt

profilerVolt:
  className: SerginhoLD\Phalcon\WebProfiler\View\Volt
  shared: true
  arguments:
    - { type: service, name: profilerView }
  calls:
    - method: setOptions
      arguments:
        - type: parameter
          value:
            path: !profilerConfig viewsCachePath
    - method: setCompiler
      arguments:
        - { type: service, name: profilerVoltCompiler }

profilerVoltCompiler:
  className: SerginhoLD\Phalcon\WebProfiler\View\Compiler
  shared: true
  arguments:
    - { type: service, name: profilerView }
  calls:
    - method: addFunction
      arguments:
        - { type: parameter, value: profiler_dump }
        - { type: parameter, value: SerginhoLD\Phalcon\WebProfiler\View\Fn\DumpFn::execute }

profilerAssets:
  className: SerginhoLD\Phalcon\WebProfiler\Service\Assets
  shared: true
  arguments:
    - { type: service, name: tag }

profilerDump:
  className: Phalcon\Support\Debug\Dump
  shared: true
  arguments:
    - type: parameter
      value:
        pre: 'margin-bottom: 0'
        other: ''
        arr: 'color: var(--bs-emphasis-color)'
        obj: 'color: var(--bs-emphasis-color)'
        bool: 'color: var(--bs-warning)'
        null: 'color: var(--bs-warning)'
        float: 'color: var(--bs-info)'
        int: 'color: var(--bs-info)'
        num: 'color: var(--bs-info)'
        str: 'color: var(--bs-teal)'
        res: 'color: var(--bs-teal)'
    - { type: parameter, value: true }

profilerStopwatch:
  className: SerginhoLD\Phalcon\WebProfiler\Service\Stopwatch
  shared: true

profilerDb:
  className: Phalcon\Db\Profiler
  shared: true

profilerLoggerAdapter:
  className: SerginhoLD\Phalcon\WebProfiler\Logger\ProfilerAdapter
  shared: true
  arguments:
    - { type: service, name: eventsManager }

profilerManager:
  className: SerginhoLD\Phalcon\WebProfiler\Service\Manager
  shared: true

SerginhoLD\Phalcon\WebProfiler\Collector\RequestCollector:
  className: SerginhoLD\Phalcon\WebProfiler\Collector\RequestCollector
  shared: true

SerginhoLD\Phalcon\WebProfiler\Collector\PerformanceCollector:
  className: SerginhoLD\Phalcon\WebProfiler\Collector\PerformanceCollector
  shared: true
  arguments:
    - { type: service, name: profilerStopwatch }

SerginhoLD\Phalcon\WebProfiler\Collector\DbCollector:
  className: SerginhoLD\Phalcon\WebProfiler\Collector\DbCollector
  shared: true
  arguments:
    - { type: service, name: profilerDb }

SerginhoLD\Phalcon\WebProfiler\Collector\LoggerCollector:
  className: SerginhoLD\Phalcon\WebProfiler\Collector\LoggerCollector
  shared: true

SerginhoLD\Phalcon\WebProfiler\Collector\ExceptionCollector:
  className: SerginhoLD\Phalcon\WebProfiler\Collector\ExceptionCollector
  shared: true

SerginhoLD\Phalcon\WebProfiler\Collector\ViewCollector:
  className: SerginhoLD\Phalcon\WebProfiler\Collector\ViewCollector
  shared: true

